[package]
name = "aoc24"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
itertools = "0.14.0"
regex = "1.11.1"

[dev-dependencies]
assert_cmd = "2.0.17"
assert_fs = "1.1.3"
predicates = "3.1.3"
